### ISSUE TITLE
this tool no longer works on my machine

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [garrettfoster13/pre2k#3]
please revert back to commit e93a36d41dae4bb5c72bdeb235e14a4dea1e478d

Thank you,

**Comment by garrettfoster13** [comment]
Can you provide some more context on why it no longer works? I'm reluctant to revert without some supporting info.

**Comment by Invoke-Mimikatz** [comment]
thank u for replying. Here's the info I'm using on my machine:

1. commit hash e93a36d41dae4bb5c72bdeb235e14a4dea1e478d
2.

**Comment by curi0usJack** [comment]
![image](https://user-images.githubusercontent.com/5608516/207727200-2d6d0983-fe6f-4f1d-b1c5-a2121f371688.png)

**Comment by garrettfoster13** [comment]
For my TrustedSec friends this version is available https://github.com/garrettfoster13/pre2k-TS
