### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Zamanry** [garrettfoster13/pre2k#4]
Hello, I am trying to install this tool using Python/Pip 3.9 or 3.10 on Kali Linux 2022.4 and keep having this issue (sudo or not):
![image](https://user-images.githubusercontent.com/28152647/208956960-8529282c-9abe-4fe3-865c-9cbb5441827a.png)

You may see mention of proxychains in there. It is confirmed working through other apt/pip installs.

Poetry is not installed in sudo or not and 3.9 or 3.10. Let me know if there is anything I can help you troubleshoot on my end.

**Comment by garrettfoster13** [comment]
Yep unfortunately this is a common issue with poetry and trying to install the tool through a proxy. You can use this version and you shouldn't have any trouble: https://github.com/garrettfoster13/pre2k-TS

**Comment by garrettfoster13** [comment]
Closing.

**Comment by garrettfoster13** [comment]
Closing
